### numpy array operations


In [2]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[2:7])#basic sclicing
print(arr[1:4:2])#with step
##negative indexing also avaliable 

[3 4 5]
[2 4]


In [7]:
arr_2d= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[1,2])#[row,col] zero se start hota hai (specific elem)
print(arr_2d[1])#row
print(arr_2d[:,1])#col


6
[4 5 6]
[2 5 8]


### sorting

In [10]:
unsorted = np.array([4,3,2,5,7,1,8])
print(np.sort(unsorted))

arr_2duno=np.array([[3,1],[1,2],[2,3]])
print(np.sort(arr_2duno,axis=0))#column wise sorting 
print(np.sort(arr_2duno,axis=1))#row wise sorting 




[1 2 3 4 5 7 8]
[[1 1]
 [2 2]
 [3 3]]
[[1 3]
 [1 2]
 [2 3]]


### filtering

In [11]:
number = np.array([1,2,3,4,5,6,7,8])
even = number[number%2==0]
print(even)


[2 4 6 8]


### filter with mask


In [12]:
mask = number > 5
print(number[mask])

[6 7 8]


### fancy indexing vs np.where()

In [14]:
indices = [0,2,4]
print(number[indices])#sida index lake deta hai

where_result = np.where(number>5)
print(number[where_result])

[1 3 5]
[6 7 8]


In [ ]:
condition_array = np.where(number>5,number*2,number)
print(condition_array)#it is like if or else condition statement if(number>5){number*2}else{number}

[ 1  2  3  4  5 12 14 16]


### adding and removing data

In [23]:
arr_1=np.array([1,2,3])
arr_2=np.array([2,3,4])
combined = arr_1+arr_2
print(combined)
combined = np.concatenate((arr_1,arr_2))
print(combined)


[3 5 7]
[1 2 3 2 3 4]


### array compatibility

In [24]:
a = np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([5,6,7])
print(a.shape==b.shape)

True


In [27]:
original = np.array([[1,2],[3,4],[8,9]])
newrow = np.array([5,6])
withnewrow = np.vstack((original,newrow))
print(original)
print(withnewrow)

newcol = np.array([[7],[8],[6]])
withnewcol=np.hstack((original,newcol))
print(withnewcol) 


[[1 2]
 [3 4]
 [8 9]]
[[1 2]
 [3 4]
 [8 9]
 [5 6]]
[[1 2 7]
 [3 4 8]
 [8 9 6]]


In [30]:
arrop=np.array([1,2,3,4,5])
deleted = np.delete(arrop,2)
print(deleted)

[1 2 4 5]
