## numpy array and basics 

In [4]:
import numpy as np

In [5]:
arr_1d=np.array([1,2,3,4,5])
print(arr_1d)
arr_2d=np.array([[1,2,3],[2,3,4]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [2 3 4]]


---
### list vs array

In [8]:
py_list=[1,2,3]#list multiplicatioin
print(py_list*2)

np_array= np.array([1,2,3])#element wise multiplicatopn
print(np_array*2)

import time 
start = time.time()
py_list=[i*2 for i in range(100000)]
print(time.time()-start)

start = time.time()
np_array=np.arange(1000000)*2
print(time.time()-start)

[1, 2, 3, 1, 2, 3]
[2 4 6]
0.0032761096954345703
0.003607034683227539


---
### creating array from scratch


In [15]:
zeros=np.zeros((3,4))
print(zeros)

ones = np.ones((3,4))
print(ones)

full = np.full((2,2),7)
print(full)

random = np.random.random((2,3))
print(random)

sequence=np.arange(0,10,1)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]
[[0.52745803 0.91252147 0.28502162]
 [0.6723293  0.66501651 0.4788497 ]]
[0 1 2 3 4 5 6 7 8 9]


### vector matrix and tensor


In [ ]:
vector = np.array([1,2,3])
print(vector)

matrix = np.matrix([[1,2,3],[1,2,3]])
print(matrix)

#tensor -- multiple dimensins

[1 2 3]
[[1 2 3]
 [1 2 3]]


### array prop

In [17]:
arr= np.array([[1,2,3],[1,22,3]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(2, 3)
2
6
int64


### array reshaping

In [25]:
arr=np.arange(12)
print(arr)

reshapes = arr.reshape((3,4))
print(reshapes)

raveled = reshapes.ravel()#return view instead of copy
print(raveled)

#transpose
transpose=reshapes.T
print(transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
